<nav class=" navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="<?= BASE_URL ?>">
            <img src="<?= BASE_URL ?>/views/<?= THEME ?>/img/klaus.png"
                 alt="TAGrain"
                 width="60">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                        <a class="nav-link" href="<?= BASE_URL . '/add.php' ?>">Ajouter une image</a>
                </li>

                <?php if (!isset($_SESSION['user'])) : ?>
                    <li class="nav-item active">
                        <a class="nav-link" href="<?= BASE_URL; ?>/blog.php">Blog</a>
                    </li>
                <?php else : ?>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Blog
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="<?= BASE_URL; ?>/blog.php">Consulter les articles</a>
                            <a class="dropdown-item" href="<?= BASE_URL; ?>/blog/mes-articles.php">Mes articles</a>
                            <a class="dropdown-item" href="<?= BASE_URL; ?>/blog/add.php">Ajouter un article</a>
                        </div>
                    </li>
                <?php endif; ?>

            </ul>
            <ul class="navbar-nav">
                <?php if (isset($_SESSION['user'])) : ?>
                    <li class="dropdown">
                        <button class="btn btn-outline-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user-astronaut"></i> <?= ($_SESSION['user']['username']); ?>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#"><i class="fa fa-user-circle"></i> Mon Compte</a>
                            <a class="dropdown-item" href="#"><i class="fa fa-cog"></i> Préférences</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="<?= BASE_URL ?>/logout.php"><i class="fa fa-sign-out-alt"></i> Déconnexion</a>
                        </div>
                    </li>
                <?php else : ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= BASE_URL; ?>/signup.php"><i class="fa fa-user-plus"></i> Inscription</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= BASE_URL; ?>/login.php"><i class="fa fa-user-astronaut"></i> Connexion</a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>