<?php include THEME_PATH . DS . 'header.phtml'; ?>

<form class="form-signin text-center" method="POST">
    <a href="<?= BASE_URL ?>"><img src="<?= BASE_URL ?>/views/<?= THEME ?>/img/americandad.svg"
                                   alt="Roger" width="180">
    </a>

    <h1 class="h3 mb-3 font-weight-normal text-light">inscription</h1>

    <?php if (!empty($errors)) : ?>
        <?php foreach ($errors as $err) : ?>
            <div class="alert alert-danger"><?= $err; ?></div>
        <?php endforeach; ?>
    <?php endif; ?>

    <div class="form-group">
        <label for="username" class="sr-only">Identifiant</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Username" value="<?= $username; ?>" required autofocus>
        <div id="hasUser" class="invalid-feedback form-text text-left">Ce nom d'utilisateur n'est pas autorisé. Réessayez.</div>
    </div>

    <div class="form-group">
        <label for="email" class="sr-only">Email</label>
        <input type="text" id="email" name="email" class="form-control" placeholder="Email" value="<?= $email; ?>" required>
    </div>

    <div class="form-group">
        <label for="password" class="sr-only">Mot de passe</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
    </div>

    <div class="form-group">
        <label for="confirmPassword" class="sr-only">Confirmer Mot de passe</label>
        <input type="password" id="confirmPassword" name="confirmPassword" class="form-control" placeholder="Confirmer mot de passe" required>
    </div>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Enregistrer</button>

    <small class="form-text text-muted">
        <a href="login.php" class="text-light">Se connecter à un compte existant</a>
    </small>

    <p class="mt-5 mb-3 text-muted">&copy; <?= date('Y'); ?></p>
</form>

<script src="<?= BASE_URL ?>/views/<?= THEME ?>/js/signup.js"></script>

<?php include THEME_PATH . DS . 'footer.phtml'; ?>
