<?php include THEME_PATH . DS . 'header.phtml'; ?>

<div class="container column">

<form class="form-signin text-center" method="POST">
    <h1 class="h3 mb-3 font-weight-normal">Inscription</h1>

    <?php if (!empty($errors)) : ?>
        <?php foreach ($errors as $err) : ?>
            <div class="alert alert-danger"><?= $err; ?></div>
        <?php endforeach; ?>
    <?php endif; ?>

    <div class="form-group">
        <label for="username" class="sr-only">Username</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Username" value="<?= $username; ?>" required autofocus >
        <small id=hasUser" class="invalid-feedback form-text text-left">Ce nom d'utilisateur n'est pas autorisé. Réessayez</small>
    </div>

    <div class="form-group">
        <label for="email" class="sr-only">Password</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Email" required value="<?= $email; ?>">
    </div>


    <div class="form-group">
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
    </div>

    <div class="form-group">
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Confirmez le Mot de passe" required>
    </div>

    <button class="btn btn-lg btn-primary btn-block" type="submit">S'inscrire</button>
    <p class="mt-5 mb-3 text-muted">&copy; <?= date('Y') ?></p>
</form>

<script src="<?= BASE_URL ?>/views/<?= THEME ?>/js/signup.js"></script>>

</div>

<?php include THEME_PATH . DS . 'footer.phtml'; ?>


